Repository razrabs-media/articles-test, pull requests merged in 2022-06, with the labels that each got.

#209 Add files via upload
  cosmo10/post101.md
Labels: bug

#214 Add files via upload
  dark3/dark.md
Labels: dark matter

#215 Add files via upload
  dark3/dark.md
Labels: dark matter

#222 Add files via upload
  saturn.md
Labels: статья

#223 Add files via upload
  mars.md
Labels: Проверка

#226 added firest real article
  fill-column-0/preview.png
  fill-column-0/staytogether.md
Labels: Колонка Фила

#229 fixed layout
  fill-column-0/preview.png
  fill-column-0/staytogether.md
Labels: Колонка Фила, Позиция сообщества

#231 Add files via upload
  how-to-become-a-team-leader/how-to-beacome.md
Labels: Cтащено с хабра

#232 Add files via upload
  how-to-become-a-team-leader_1/how-to-beacome.md
Labels: Cтащено с хабра

#233 Add files via upload
  it-specialist-in-usa/it-specialist-usa.md
Labels: Cтащено с хабра

#235 Add files via upload
  maket/test.md
Labels: maket

#236 Add files via upload
  post201.md
Labels: post

#237 Add files via upload
  post203/post201.md
Labels: post

#246 Посты и темной материи и океане
  Правда, что мировой океан изучен хуже космоса/Правда, что мировой океан изучен хуже космоса.md
  Тёмная материя/Тёмная материя.md
Labels: Космос, Темная материя

#247 Add files via upload
  Каковы размеры Вселенной/Каковы размеры Вселенной.md
  Когда во Вселенной появились первые звезды/Когда во Вселенной появились первые звезды.md
Labels: Космос, Вселенная

#248 Add files via upload
  Во время грозы в небе образуется… антиматерия/Во время грозы в небе образуется… антиматерия.md
  Зафиксированы мощнейшие в истории внеземные радиосигналы/Зафиксированы мощнейшие в истории внеземные радиосигналы.md
  Как выглядела бы черная дыра рядом с Землей/Как выглядела бы черная дыра рядом с Землей.md
Labels: Космос, На грани фантастики

#249 Add files via upload
  Как выглядит цветение фитопланктона из космоса/Как выглядит цветение фитопланктона из космоса.md
  Как марсоход Curiosity фотографирует сам себя/Как марсоход Curiosity фотографирует сам себя.md
  Можно ли безопасно пролететь через пояс астероидов/Можно ли безопасно пролететь через пояс астероидов.md
  Можно ли сфотографировать строение атома/Можно ли сфотографировать строение атома.md
  Отпечатки ладоней возрастом 13 000 лет/Отпечатки ладоней возрастом 13 000 лет.md
  Правда, что мировой океан изучен хуже космоса/Правда, что мировой океан изучен хуже космоса.md
Labels: Космос, Чтиво, От редакции

#251 Add files via upload
  Самая большая планета – ROXs 42Bb/Самая большая планета – ROXs 42Bb.md
  Сколько энергии содержится в урагане/Сколько энергии содержится в урагане.md
  Ученые обнаружили возможные следы предыдущей Вселенной/Ученые обнаружили возможные следы предыдущей Вселенной.md
Labels: Космос, Чтиво, Тема дня, Что читаем мы

#253 Add files via upload
  test-xss.md
Labels: Чтиво

#256 Add files via upload
  5 полезных примеров кода на Python — копия (2)/jjqoxswcr5qbvgi5bvbqds8r2dy.jpeg
  5 полезных примеров кода на Python — копия (2)/post5.md
  5 полезных примеров кода на Python — копия (3)/jjqoxswcr5qbvgi5bvbqds8r2dy.jpeg
  5 полезных примеров кода на Python — копия (3)/post5.md
  5 полезных примеров кода на Python — копия (4)/jjqoxswcr5qbvgi5bvbqds8r2dy.jpeg
  5 полезных примеров кода на Python — копия (4)/post5.md
  5 полезных примеров кода на Python — копия (5)/jjqoxswcr5qbvgi5bvbqds8r2dy.jpeg
  5 полезных примеров кода на Python — копия (5)/post5.md
  5 полезных примеров кода на Python — копия (6)/jjqoxswcr5qbvgi5bvbqds8r2dy.jpeg
  5 полезных примеров кода на Python — копия (6)/post5.md
  5 полезных примеров кода на Python — копия (7)/jjqoxswcr5qbvgi5bvbqds8r2dy.jpeg
  5 полезных примеров кода на Python — копия (7)/post5.md
  5 полезных примеров кода на Python — копия (8)/jjqoxswcr5qbvgi5bvbqds8r2dy.jpeg
  5 полезных примеров кода на Python — копия (8)/post5.md
  5 полезных примеров кода на Python — копия/jjqoxswcr5qbvgi5bvbqds8r2dy.jpeg
  5 полезных примеров кода на Python — копия/post5.md
  5 полезных примеров кода на Python/jjqoxswcr5qbvgi5bvbqds8r2dy.jpeg
  5 полезных примеров кода на Python/post5.md
  Баг-репорт — копия (2)/bug-report-correct.png
  Баг-репорт — копия (2)/bug-report-not-correct.jpg
  Баг-репорт — копия (2)/post1.md
  Баг-репорт — копия (2)/smiling-cat-creepy-cat.gif
  Баг-репорт — копия (3)/bug-report-correct.png
  Баг-репорт — копия (3)/bug-report-not-correct.jpg
  Баг-репорт — копия (3)/post1.md
  Баг-репорт — копия (3)/smiling-cat-creepy-cat.gif
  Баг-репорт — копия (4)/bug-report-correct.png
  Баг-репорт — копия (4)/bug-report-not-correct.jpg
  Баг-репорт — копия (4)/post1.md
  Баг-репорт — копия (4)/smiling-cat-creepy-cat.gif
  Баг-репорт — копия (5)/bug-report-correct.png
  Баг-репорт — копия (5)/bug-report-not-correct.jpg
  Баг-репорт — копия (5)/post1.md
  Баг-репорт — копия (5)/smiling-cat-creepy-cat.gif
  Баг-репорт — копия (6)/bug-report-correct.png
  Баг-репорт — копия (6)/bug-report-not-correct.jpg
  Баг-репорт — копия (6)/post1.md
  Баг-репорт — копия (6)/smiling-cat-creepy-cat.gif
  Баг-репорт — копия (7)/bug-report-correct.png
  Баг-репорт — копия (7)/bug-report-not-correct.jpg
  Баг-репорт — копия (7)/post1.md
  Баг-репорт — копия (7)/smiling-cat-creepy-cat.gif
  Баг-репорт — копия (8)/bug-report-correct.png
  Баг-репорт — копия (8)/bug-report-not-correct.jpg
  Баг-репорт — копия (8)/post1.md
  Баг-репорт — копия (8)/smiling-cat-creepy-cat.gif
  Баг-репорт — копия/bug-report-correct.png
  Баг-репорт — копия/bug-report-not-correct.jpg
  Баг-репорт — копия/post1.md
  Баг-репорт — копия/smiling-cat-creepy-cat.gif
  Баг-репорт/bug-report-correct.png
  Баг-репорт/bug-report-not-correct.jpg
  Баг-репорт/post1.md
  Баг-репорт/smiling-cat-creepy-cat.gif
Labels: post

#257 Add files via upload
  Начало работы с HTML/1234.png
  Начало работы с HTML/ami-fat-cat.gif
  Начало работы с HTML/post6.md
Labels: post

#264 Add files via upload
  1 (10)/bug-report-correct.png
  1 (10)/bug-report-not-correct.jpg
  1 (10)/post1.md
  1 (10)/smiling-cat-creepy-cat.gif
  1 (2)/jjqoxswcr5qbvgi5bvbqds8r2dy.jpeg
  1 (2)/post5.md
  1 (3)/jjqoxswcr5qbvgi5bvbqds8r2dy.jpeg
  1 (3)/post5.md
  1 (4)/jjqoxswcr5qbvgi5bvbqds8r2dy.jpeg
  1 (4)/post5.md
  1 (5)/jjqoxswcr5qbvgi5bvbqds8r2dy.jpeg
  1 (5)/post5.md
  1 (6)/jjqoxswcr5qbvgi5bvbqds8r2dy.jpeg
  1 (6)/post5.md
  1 (7)/jjqoxswcr5qbvgi5bvbqds8r2dy.jpeg
  1 (7)/post5.md
  1 (8)/jjqoxswcr5qbvgi5bvbqds8r2dy.jpeg
  1 (8)/post5.md
  1 (9)/jjqoxswcr5qbvgi5bvbqds8r2dy.jpeg
  1 (9)/post5.md
  1/jjqoxswcr5qbvgi5bvbqds8r2dy.jpeg
  1/post5.md
Labels: post

#267 Add files via upload
  100 (272).md
  100 (273).md
  100 (274).md
  100 (275).md
  100 (276).md
  100 (277).md
  100 (278).md
  100 (279).md
  100 (280).md
  100 (281).md
  100 (282).md
  100 (283).md
  100 (284).md
  100 (285).md
  100 (286).md
  100 (287).md
  100 (288).md
  100 (289).md
  100 (290).md
  100 (291).md
  100 (292).md
  100 (293).md
  100 (294).md
  100 (295).md
  100 (296).md
  100 (297).md
  100 (298).md
  100 (299).md
  100 (300).md
  100 (301).md
Labels: post

#269 Add files via upload
  100 (1).md
  100 (10).md
  100 (11).md
  100 (12).md
  100 (13).md
  100 (14).md
  100 (15).md
  100 (16).md
  100 (17).md
  100 (18).md
  100 (19).md
  100 (2).md
  100 (20).md
  100 (21).md
  100 (22).md
  100 (23).md
  100 (24).md
  100 (25).md
  100 (26).md
  100 (27).md
  100 (28).md
  100 (29).md
  100 (3).md
  100 (30).md
  100 (4).md
  100 (5).md
  100 (6).md
  100 (7).md
  100 (8).md
  100 (9).md
Labels: post

#270 Add files via upload
  300 (234).md
  300 (235).md
  300 (236).md
  300 (237).md
  300 (238).md
  300 (239).md
  300 (247).md
  300 (248).md
  300 (260).md
  300 (261).md
  300 (262).md
  300 (286).md
  300 (287).md
  300 (288).md
  300 (289).md
  300 (290).md
  300 (291).md
  300 (292).md
  300 (293).md
  300 (294).md
  300 (295).md
  300 (318).md
  300 (319).md
  300 (320).md
  300 (321).md
  300 (322).md
  300 (323).md
  300 (324).md
  300 (325).md
  300 (326).md
  300 (338).md
  300 (339).md
  300 (340).md
  300 (341).md
  300 (342).md
  300 (343).md
Labels: post

#271 Add files via upload
  400 (100).md
  400 (113).md
  400 (116).md
  400 (129).md
  400 (139).md
  400 (153).md
  400 (164).md
  400 (177).md
  400 (190).md
  400 (214).md
  400 (217).md
  400 (231).md
  400 (24).md
  400 (244).md
  400 (255).md
  400 (268).md
  400 (278).md
  400 (289).md
  400 (299).md
  400 (309).md
  400 (319).md
  400 (334).md
  400 (338).md
  400 (339).md
  400 (346).md
  400 (36).md
  400 (46).md
  400 (80).md
  400 (88).md
  400 (96).md
Labels: post
