Repository razrabs-media/articles-test, pull requests merged in 2022-08, with the labels that each got.

#306 added test text
  f2test/preview.png
  f2test/staytogether.md
Labels: Колонка Фила

#307 Add files via upload
  На чем мы полетим к звездам Самые невероятные проекты освоения космоса/На чем мы полетим к звездам Самые невероятные проекты освоения космоса.md
Labels: cosmotest, cтатья01

#313 Add files via upload
  Первая фотография Земли из космоса____1/Первая фотография Земли из космоса.md
Labels: article

#314 Add files via upload
  Каковы размеры Вселенной_01/Каковы размеры Вселенной.md
Labels: cosmotest, cтатья01

#319 Markdown tutorial
  Markdown_tutorial/Markdown.md
Labels: cosmotest, Cтащено с хабра, cтатья01

#320 update md tutorial
  Markdown_tutorial/Markdown.md
Labels: bug, Cтащено с хабра

#323 Add files via upload
  apanasik-iz-razrabotchi/apanasik-iz-razrabotchikov-igr-v-razrabotchiki-servisa-balancy-dlya-razrabotchikov-igr.md
Labels: article

#326 Add files via upload
  apanasik-iz-razrabotchi_1_1_1/adminka_new_1.png
  apanasik-iz-razrabotchi_1_1_1/adminka_old.png
  apanasik-iz-razrabotchi_1_1_1/apanasik-iz-razrabotchikov-igr-v-razrabotchiki-servisa-balancy-dlya-razrabotchikov-igr.md
  apanasik-iz-razrabotchi_1_1_1/balancy-preview.png
  apanasik-iz-razrabotchi_1_1_1/balancy_conditions.png
  apanasik-iz-razrabotchi_1_1_1/balancy_docs.png
  apanasik-iz-razrabotchi_1_1_1/balancy_nodes.png
  apanasik-iz-razrabotchi_1_1_1/balancy_templates.png
  apanasik-iz-razrabotchi_1_1_1/cyprus_home.jpg
  apanasik-iz-razrabotchi_1_1_1/hero-masters.jpg
  apanasik-iz-razrabotchi_1_1_1/unnynet.png
  apanasik-iz-razrabotchi_1_1_1/unnynet_old.png
  apanasik-iz-razrabotchi_1_1_1/unnyworld-prototype.jpg
Labels: article

#331 Add files via upload
  clay.md
  julia-joppien-XFUqd0u5U7w-unsplash.jpg
Labels: bug, article

#332 Add files via upload
  Во время грозы в небе образуется… антиматерия_01/Во время грозы в небе образуется… антиматерия.md
Labels: FORK

#339 Add files via upload
  how to be a middle dev__1/Как стать мидлом или сеньором-разработчиком.md
Labels: article, alert

#340 Add files via upload
  how to be a middle dev__1/Как стать мидлом или сеньором-разработчиком.md
Labels: article, alert, article-test

#348 Add files via upload
  how to teach developers/how-to-teach-developers.md
  how to teach developers/preview.jpg
Labels: Редакция

#349 Add files via upload
  how to teach developers/how-to-teach-developers.md
Labels: Редакция

#350 Add files via upload
  how to teach developers/how-to-teach-developers.md
Labels: Редакция

#351 Add files via upload
  corporate/corporate.md
  corporate/preview.jpg
Labels: bug, article-test

#352 Add files via upload
  2pizza-story/2pizza-story.md
  2pizza-story/connected-to-freedom.jpg
  2pizza-story/preview.jpg
Labels: Редакция

#353 Add files via upload
  2pizza-story_1/2pizza-story.md
  2pizza-story_1/connected-to-freedom.jpg
  2pizza-story_1/preview.jpg
Labels: Редакция

#316 how to become a middle developer
  how to be a middle dev/Как стать мидлом или сеньором-разработчиком.md
Labels: alert

#370 Add files via upload
  BDSM-girl 223/BDSMgirl.md
  BDSM-girl 223/image1.jpg
  BDSM-girl 223/image10.png
  BDSM-girl 223/image11.jpg
  BDSM-girl 223/image12.jpg
  BDSM-girl 223/image13.jpg
  BDSM-girl 223/image14.jpg
  BDSM-girl 223/image15.jpg
  BDSM-girl 223/image16.jpg
  BDSM-girl 223/image17.jpg
  BDSM-girl 223/image18.jpg
  BDSM-girl 223/image19.jpg
  BDSM-girl 223/image2.jpg
  BDSM-girl 223/image20.jpg
  BDSM-girl 223/image21.png
  BDSM-girl 223/image22.jpg
  BDSM-girl 223/image23.jpg
  BDSM-girl 223/image24.jpg
  BDSM-girl 223/image25.jpg
  BDSM-girl 223/image3.jpg
  BDSM-girl 223/image4.png
  BDSM-girl 223/image5.jpg
  BDSM-girl 223/image6.jpg
  BDSM-girl 223/image7.jpg
  BDSM-girl 223/image8.png
  BDSM-girl 223/image9.jpg
  BDSM-girl 223/preview.jpg
Labels: Редакция

#404 test podlodka article
  podlodka/podlodka.md
  podlodka/preview.jpg
Labels: Интервью, История

#405 Add files via upload
  podlodka/podlodka.md
Labels: Интервью, История

#412 Add files via upload
  Темная материя1/Темная материя.md
Labels: bug, documentation, duplicate, enhancement, good first issue, help wanted, invalid, question, wontfix, post, test, article, космо, testtest, cosmotest, test3, tets4, test5, test6, test7, test8, test9, test10, alert, Колонка Фила, Cтащено с хабра, test11, Статьи с картинками для Антона, space, xss, maket, dark matter, статья, cтатья01, странности, inspection, Позиция сообщества, Моя работа, Космос, Чтиво, Темная материя, Вселенная, На грани фантастики, От редакции, Солнечная система, Выбор редакции, Тема дня, Что читаем мы, List, Тест, тест 1, Тест 2, long, article-test, FORK, Редакция, Интервью, История
