Repository razrabs-media/articles-test, pull requests merged in 2022-07, with the labels that each got.

#273 Add files via upload
  Lyuba.md
Labels: bug

#282 Add files via upload
  java1.md
Labels: space

#292 Add files via upload
  ```.md
Labels: bug

#293 Add files via upload
  50 интересных фактов о Луне/50 интересных фактов о Луне.md
Labels: космо, space

#296 Add files via upload
  Ураган.md
Labels: тест 1

#297 Add files via upload
  Звезды.md
Labels: Тест 2

#298 Add files via upload
  Вольфа-Райе.md
Labels: тест 1

#299 Add files via upload
  скорость.md
Labels: тест 1

#230 Add files via upload
  test_post_md_01/md.md
Labels: bug, article

#302 Add files via upload
  большой .md
Labels: long
